# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UberDriver' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UberDriver
	pod 'Firebase'
	pod 'Firebase/Core'
	pod 'Firebase/Storage'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
    pod 'SCLAlertView'

  target 'UberDriverTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UberDriverUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
